services:
  camclient:
    build: .
    container_name: camclient
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # network_mode: host
    # networks:
    #   # internal:
    #   #   driver: bridge
    #   external:
    #     driver: host

  webserver:
    build: .
    container_name: webserver
    volumes:
      - .:/code
    ports:
      - "8080:8080"
